// <auto-generated />
using System;
using LaExpedicion.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LaExpedicion.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260309013134_AgregarNuevosCatalogosPop")]
    partial class AgregarNuevosCatalogosPop
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LaExpedicion.Domain.Entities.Estadistica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<int>("Energia")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Fuerza")
                        .HasColumnType("int");

                    b.Property<int>("Magia")
                        .HasColumnType("int");

                    b.Property<int>("Mana")
                        .HasColumnType("int");

                    b.Property<Guid>("PersonajeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Salud")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonajeId")
                        .IsUnique();

                    b.ToTable("Estadisticas", (string)null);
                });

            modelBuilder.Entity("LaExpedicion.Domain.Entities.Etiqueta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Etiquetas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f19dd3d1-3837-4a9a-80d1-190a8f128d9c"),
                            Activo = false,
                            Descripcion = "Especialista en salir con vida de situaciones biológicas extremas.",
                            Eliminado = false,
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaModificacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Superviviente",
                            UsuarioCreacion = "",
                            UsuarioModificacion = ""
                        },
                        new
                        {
                            Id = new Guid("0c336332-db1e-4308-a678-e5309c42a795"),
                            Activo = false,
                            Descripcion = "Mutante entrenado para rastrear y cazar monstruos a cambio de monedas.",
                            Eliminado = false,
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaModificacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Brujo",
                            UsuarioCreacion = "",
                            UsuarioModificacion = ""
                        },
                        new
                        {
                            Id = new Guid("aaef9db3-a67f-46f8-aec7-e37355d454e2"),
                            Activo = false,
                            Descripcion = "Guardián de la paz y la justicia, sensible a fuerzas místicas.",
                            Eliminado = false,
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaModificacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Jedi",
                            UsuarioCreacion = "",
                            UsuarioModificacion = ""
                        },
                        new
                        {
                            Id = new Guid("2a3dfde7-ce67-4205-8f0f-08f3d6287a0b"),
                            Activo = false,
                            Descripcion = "Especialista en tácticas de rescate, armas de fuego y supervivencia extrema.",
                            Eliminado = false,
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaModificacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Agente S.T.A.R.S.",
                            UsuarioCreacion = "",
                            UsuarioModificacion = ""
                        },
                        new
                        {
                            Id = new Guid("e8f3cbb0-78a4-4001-85d1-9d923019ed86"),
                            Activo = false,
                            Descripcion = "Maestro del sigilo, el parkour y el uso de la hoja oculta bajo las sombras.",
                            Eliminado = false,
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaModificacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Asesino de la Hermandad",
                            UsuarioCreacion = "",
                            UsuarioModificacion = ""
                        },
                        new
                        {
                            Id = new Guid("d1111111-1111-1111-1111-111111111111"),
                            Activo = false,
                            Descripcion = "Héroe con atributos muy bajos, ¿estará destinado para apuntar a lo grande?",
                            Eliminado = false,
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaModificacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Novato",
                            UsuarioCreacion = "",
                            UsuarioModificacion = ""
                        },
                        new
                        {
                            Id = new Guid("d2222222-2222-2222-2222-222222222222"),
                            Activo = false,
                            Descripcion = "Un combatiente estándar y capaz, listo para forjar su propio destino en este peligroso mundo.",
                            Eliminado = false,
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaModificacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Aventurero",
                            UsuarioCreacion = "",
                            UsuarioModificacion = ""
                        },
                        new
                        {
                            Id = new Guid("d3333333-3333-3333-3333-333333333333"),
                            Activo = false,
                            Descripcion = "Destaca entre la multitud. Sus habilidades sobresalientes le auguran un futuro brillante y lleno de victorias.",
                            Eliminado = false,
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaModificacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Talento Nato",
                            UsuarioCreacion = "",
                            UsuarioModificacion = ""
                        },
                        new
                        {
                            Id = new Guid("d4444444-4444-4444-4444-444444444444"),
                            Activo = false,
                            Descripcion = "Héroe imparable, hay muchas expectativas puestas sobre ti. El mundo entero observa tus pasos.",
                            Eliminado = false,
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaModificacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Genio",
                            UsuarioCreacion = "",
                            UsuarioModificacion = ""
                        });
                });

            modelBuilder.Entity("LaExpedicion.Domain.Entities.Expedicion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("Dinero")
                        .HasPrecision(14, 2)
                        .HasColumnType("float(14)");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<int>("Experiencia")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Expediciones", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("64fea296-23f9-430e-bec4-f5d01dc86509"),
                            Activo = false,
                            Descripcion = "Investiga los extraños incidentes y desapariciones en las oscuras montañas Arklay.",
                            Dinero = 1500.0,
                            Eliminado = false,
                            Experiencia = 500,
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaModificacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Incidente en la Mansión Spencer",
                            UsuarioCreacion = "",
                            UsuarioModificacion = ""
                        },
                        new
                        {
                            Id = new Guid("83262a7b-6916-4ec4-b4a6-bb62cbfee247"),
                            Activo = false,
                            Descripcion = "Una peligrosa travesía para destruir un objeto de inmenso poder en los fuegos del Monte del Destino.",
                            Dinero = 0.0,
                            Eliminado = false,
                            Experiencia = 2000,
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaModificacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Viaje a Mordor",
                            UsuarioCreacion = "",
                            UsuarioModificacion = ""
                        },
                        new
                        {
                            Id = new Guid("65fcf63f-94fb-4f1a-abb6-004a02b078c3"),
                            Activo = false,
                            Descripcion = "Abrete paso entre hordas de infectados y mutantes antes de que la ciudad sea purgada del mapa.",
                            Dinero = 500.0,
                            Eliminado = false,
                            Experiencia = 1500,
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaModificacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Escape de Raccoon City",
                            UsuarioCreacion = "",
                            UsuarioModificacion = ""
                        },
                        new
                        {
                            Id = new Guid("067cdc49-de25-4e88-bec6-42f9aa627dba"),
                            Activo = false,
                            Descripcion = "Resiste el asedio del Rey de la Noche y su ejército de caminantes blancos.",
                            Dinero = 2500.0,
                            Eliminado = false,
                            Experiencia = 3000,
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaModificacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Defensa de Invernalia",
                            UsuarioCreacion = "",
                            UsuarioModificacion = ""
                        },
                        new
                        {
                            Id = new Guid("c3333333-3333-3333-3333-333333333333"),
                            Activo = false,
                            Descripcion = "Sobrevive a dragones, rescata rehenes en el lago negro y encuentra la copa en el laberinto.",
                            Dinero = 10000.0,
                            Eliminado = false,
                            Experiencia = 2500,
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaModificacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Torneo de los Tres Magos",
                            UsuarioCreacion = "",
                            UsuarioModificacion = ""
                        });
                });

            modelBuilder.Entity("LaExpedicion.Domain.Entities.ExpedicionRealizada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<double>("DineroGanado")
                        .HasPrecision(14, 2)
                        .HasColumnType("float(14)");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<Guid>("ExpedicionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ExperienciaGanada")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PersonajeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExpedicionId");

                    b.HasIndex("PersonajeId");

                    b.ToTable("ExpedicionRealizadas", (string)null);
                });

            modelBuilder.Entity("LaExpedicion.Domain.Entities.Inventario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<bool>("Equipado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonajeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UsosRestantes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("PersonajeId");

                    b.ToTable("Inventario", (string)null);
                });

            modelBuilder.Entity("LaExpedicion.Domain.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Items", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f19dd3d1-3837-4a9a-80d1-190a8f128d9c"),
                            Activo = false,
                            Descripcion = "Planta medicinal clásica que restaura una cantidad moderada de salud. Mejor si se combina.",
                            Eliminado = false,
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaModificacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Hierba Verde",
                            UsuarioCreacion = "",
                            UsuarioModificacion = ""
                        },
                        new
                        {
                            Id = new Guid("0c336332-db1e-4308-a678-e5309c42a795"),
                            Activo = false,
                            Descripcion = "La hoja destructora del mal, forjada por diosas antiguas.",
                            Eliminado = false,
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaModificacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Espada Maestra",
                            UsuarioCreacion = "",
                            UsuarioModificacion = ""
                        },
                        new
                        {
                            Id = new Guid("aaef9db3-a67f-46f8-aec7-e37355d454e2"),
                            Activo = false,
                            Descripcion = "Suerte líquida. Quien la bebe tendrá éxito en todo lo que intente.",
                            Eliminado = false,
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaModificacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Poción Felix Felicis",
                            UsuarioCreacion = "",
                            UsuarioModificacion = ""
                        },
                        new
                        {
                            Id = new Guid("1e2dfb2e-9264-4d8f-8a7e-b9a174bb1192"),
                            Activo = false,
                            Descripcion = "Cilindro presurizado que restaura la salud por completo de forma casi instantánea.",
                            Eliminado = false,
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaModificacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Spray de Primeros Auxilios",
                            UsuarioCreacion = "",
                            UsuarioModificacion = ""
                        },
                        new
                        {
                            Id = new Guid("ef70e69f-798f-4923-a8a2-3d88d719eb0f"),
                            Activo = false,
                            Descripcion = "Un arma elegante para una era más civilizada. Capaz de cortar casi cualquier material.",
                            Eliminado = false,
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaModificacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Sable de Luz",
                            UsuarioCreacion = "",
                            UsuarioModificacion = ""
                        },
                        new
                        {
                            Id = new Guid("7ea6bd92-05ba-4dea-899d-408e95d28031"),
                            Activo = false,
                            Descripcion = "Otorga invisibilidad a su portador, pero corrompe su mente lentamente.",
                            Eliminado = false,
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaModificacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "El Anillo Único",
                            UsuarioCreacion = "",
                            UsuarioModificacion = ""
                        },
                        new
                        {
                            Id = new Guid("b5e4edfa-3c3f-4a77-83e7-b34498148df3"),
                            Activo = false,
                            Descripcion = "Dispositivo de muñeca que dispara un fluido sintético con la resistencia del acero.",
                            Eliminado = false,
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaModificacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Lanzaredes",
                            UsuarioCreacion = "",
                            UsuarioModificacion = ""
                        });
                });

            modelBuilder.Entity("LaExpedicion.Domain.Entities.ItemModificador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<string>("EstadisticaAfectada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ValorAjuste")
                        .HasPrecision(0, 5)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemsModificadores", (string)null);
                });

            modelBuilder.Entity("LaExpedicion.Domain.Entities.Personaje", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<Guid>("EtiquetaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UsuarioModificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EtiquetaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Personajes", (string)null);
                });

            modelBuilder.Entity("LaExpedicion.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SegundoApellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LaExpedicion.Domain.Entities.Estadistica", b =>
                {
                    b.HasOne("LaExpedicion.Domain.Entities.Personaje", "Personaje")
                        .WithOne("Estadistica")
                        .HasForeignKey("LaExpedicion.Domain.Entities.Estadistica", "PersonajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personaje");
                });

            modelBuilder.Entity("LaExpedicion.Domain.Entities.ExpedicionRealizada", b =>
                {
                    b.HasOne("LaExpedicion.Domain.Entities.Expedicion", "Expedicion")
                        .WithMany("ExpedicionesRealizadas")
                        .HasForeignKey("ExpedicionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LaExpedicion.Domain.Entities.Personaje", "Personaje")
                        .WithMany()
                        .HasForeignKey("PersonajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expedicion");

                    b.Navigation("Personaje");
                });

            modelBuilder.Entity("LaExpedicion.Domain.Entities.Inventario", b =>
                {
                    b.HasOne("LaExpedicion.Domain.Entities.Item", "Item")
                        .WithMany("Inventario")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LaExpedicion.Domain.Entities.Personaje", "Personaje")
                        .WithMany("Inventario")
                        .HasForeignKey("PersonajeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Personaje");
                });

            modelBuilder.Entity("LaExpedicion.Domain.Entities.ItemModificador", b =>
                {
                    b.HasOne("LaExpedicion.Domain.Entities.Item", "Item")
                        .WithMany("ItemModificador")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("LaExpedicion.Domain.Entities.Personaje", b =>
                {
                    b.HasOne("LaExpedicion.Domain.Entities.Etiqueta", "Etiqueta")
                        .WithMany("Personajes")
                        .HasForeignKey("EtiquetaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LaExpedicion.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Etiqueta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("LaExpedicion.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("LaExpedicion.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaExpedicion.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("LaExpedicion.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LaExpedicion.Domain.Entities.Etiqueta", b =>
                {
                    b.Navigation("Personajes");
                });

            modelBuilder.Entity("LaExpedicion.Domain.Entities.Expedicion", b =>
                {
                    b.Navigation("ExpedicionesRealizadas");
                });

            modelBuilder.Entity("LaExpedicion.Domain.Entities.Item", b =>
                {
                    b.Navigation("Inventario");

                    b.Navigation("ItemModificador");
                });

            modelBuilder.Entity("LaExpedicion.Domain.Entities.Personaje", b =>
                {
                    b.Navigation("Estadistica");

                    b.Navigation("Inventario");
                });
#pragma warning restore 612, 618
        }
    }
}
